version: '3.4'

services:
  botapp:
    image: ${DOCKER_REGISTRY-}botapp
    build:
      context: .
      dockerfile: Bot.App/Dockerfile
    depends_on:
        - telegram-local-api      
    volumes:
        - ./conf:/app/conf 
        - telegram-bot-api-data:/var/lib/telegram-bot-api
        - telegram-bot-git-data:/app/repository
            

  telegram-local-api:
    image: aiogram/telegram-bot-api
    
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: true      
    volumes:
        - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - 8081:8081
volumes:
  telegram-bot-api-data:  
  telegram-bot-git-data:
    
